### ISSUE TITLE
fs is not defined

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb-express-router#9]
```
  1) test.attachments.js-http issue 2803 should throw 412:

      AssertionError: expected 500 to equal 412

      + expected - actual

      +412

      -500



      at /home/travis/build/pouchdb/pouchdb/tests/integration/test.attachments.js:102:27

      at tryCatch1 (/home/travis/build/pouchdb/pouchdb/node_modules/bluebird/js/main/util.js:63:19)

      at Promise$_callHandler [as _callHandler] (/home/travis/build/pouchdb/pouchdb/node_modules/bluebird/js/main/promise.js:695:13)

      at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/home/travis/build/pouchdb/pouchdb/node_modules/bluebird/js/main/promise.js:711:18)

      at Promise$_settlePromiseAt [as _settlePromiseAt] (/home/travis/build/pouchdb/pouchdb/node_modules/bluebird/js/main/promise.js:868:14)

      at Promise$_settlePromises [as _settlePromises] (/home/travis/build/pouchdb/pouchdb/node_modules/bluebird/js/main/promise.js:1006:14)

      at Promise$_rejectPromises [as _rejectPromises] (/home/travis/build/pouchdb/pouchdb/node_modules/bluebird/js/main/promise.js:999:10)

      at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/home/travis/build/pouchdb/pouchdb/node_modules/bluebird/js/main/async.js:74:12)

      at Async$consumeFunctionBuffer (/home/travis/build/pouchdb/pouchdb/node_modules/bluebird/js/main/async.js:37:14)

      at process._tickCallback (node.js:448:13)
```

See also https://github.com/pouchdb/pouchdb/pull/3889

**Comment by nolanlawson** [comment]
fixed
